sudo: false
cache:
  directories:
    - $HOME/.m2
language: java
jdk:
- oraclejdk8
os:
  - linux
script: mvn clean package
install: true
after_success:
  - "[ ${TRAVIS_PULL_REQUEST} = 'false' ] && [ ${TRAVIS_BRANCH} = 'master' ] && mvn clean package -DskipTests nexus-staging:deploy ./deploy-settings.xml"
